site_name: Authentication Kit
pages:
- Home: 'index.md'
- Interfaces: [
{AuthenticationKit.Validator: 'AuthenticationKit.Validator.md'}, 
{AuthenticationKit.User: 'AuthenticationKit.User.md'}, 
{AuthenticationKit.MutableUser: 'AuthenticationKit.MutableUser.md'}
]
- Classes: [
{AuthenticationKit.Token: 'AuthenticationKit.Token.md'}, 
{AuthenticationKit.TwoFactorProfile: 'AuthenticationKit.TwoFactorProfile.md'}
]
- Version History: 'History.md'
theme: mkdocs
include_next_prev: false